services:
  haproxy:
    image: haproxy:3.2.3-alpine
    container_name: rinha-haproxy
    volumes:
      - sockets:/sockets:rw
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "80MB"
    networks:
      - backend
    ports:
      - 9999:80
    depends_on:
      - rinha-gateway-1
      - rinha-gateway-2
      - rinha-gateway-3

  rinha-gateway-1:
    build:
      context: ./gateway
    container_name: rinha-gateway-1
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/actix.sock.1
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  rinha-gateway-2:
    build:
      context: ./gateway
    container_name: rinha-gateway-2
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/actix.sock.2
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  rinha-gateway-3:
    build:
      context: ./gateway
    container_name: rinha-gateway-3
    volumes:
      - sockets:/sockets:rw
    environment:
      - SOCKET_PATH=/sockets/actix.sock.3
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "70MB"

  rinha-database:
    build:
      context: ./database
    container_name: rinha-database
    volumes:
      - sockets:/sockets:rw
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "30MB"

volumes:
  sockets:

networks:
  backend:
    name: rinha-net
    driver: bridge
  payment-processor:
    external: true
