services:
  nginx:
    image: nginx:1.27.0-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:80"
    networks:
      - backend
    depends_on:
      - rinha-gateway-1
      - rinha-gateway-2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

  rinha-gateway-1:
    build:
      context: ./gateway-async
    container_name: rinha-gateway-1
    # As labels do Traefik foram removidas
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.6" # <--- Mais CPU
          memory: "125MB" # <--- Mais RAM

  rinha-gateway-2:
    build:
      context: ./gateway-async
    container_name: rinha-gateway-2
    # As labels do Traefik foram removidas
    networks:
      - backend
      - payment-processor
    depends_on:
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.6" # <--- Mais CPU
          memory: "125MB" # <--- Mais RAM

  rinha-db:
    build:
      context: ./database
    container_name: rinha-db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50MB"

networks:
  backend:
    name: rinha-net
    driver: bridge
  payment-processor:
    external: true
