[package]
name = "gateway-async"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
tokio = "1.46.1"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.12.22", features = ["json"] }
chrono = { version = "0.4.41", features = ["serde"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
crossbeam-queue = "0.3.12"
async-channel = "2.5.0"
mimalloc = "0.1.47"
