[package]
name = "database"
version = "0.1.0"
edition = "2024"

[dependencies]
mimalloc = "0.1.47"
actix-web = "4.11.0"
crossbeam-queue = "0.3.12"
chrono = { version = "0.4.41", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
