services:
  traefik:
    image: traefik:v3.4
    container_name: rinha-traefik
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "9999:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "180MB"
  rinha-gateway-1:
    image: ghcr.io/alan-venv/rinha-gateway:1.0
    container_name: rinha-gateway-1
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=rinha-net"
      - "traefik.http.routers.gateway.rule=Host(`localhost`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.routers.gateway.service=gateway"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"
    networks:
      - backend
      - payment-processor
    depends_on:
      - traefik
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "60MB"
  rinha-gateway-2:
    image: ghcr.io/alan-venv/rinha-gateway:1.0
    container_name: rinha-gateway-2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=rinha-net"
      - "traefik.http.routers.gateway.rule=Host(`localhost`)"
      - "traefik.http.routers.gateway.entrypoints=web"
      - "traefik.http.routers.gateway.service=gateway"
      - "traefik.http.services.gateway.loadbalancer.server.port=8080"
    networks:
      - backend
      - payment-processor
    depends_on:
      - traefik
      - rinha-db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "60MB"
  rinha-db:
    image: ghcr.io/alan-venv/rinha-database:1.0
    container_name: rinha-db
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "50MB"

networks:
  backend:
    name: rinha-net
    driver: bridge
  payment-processor:
    external: true
